### ISSUE TITLE
Cotta docs corrections

### ISSUE THREAD

**Issue by shaun-wild** [mgtriffid/cotta#5]
The KSP declaration should be as follows:

```groovy
  id 'com.google.devtools.ksp' version '1.9.24-1.0.20'
```

The property for the cotta version should be as follows:

```
cottaVersion=0.1.2
```

**Comment by mgtriffid** [comment]
Thanks for the contribution!

> cotta version

Updated this one

> KSP declaration

Hmm it turns out I really did forget to specify the versions, I decided to include it like this 
https://github.com/mgtriffid/cotta/commit/ee0bd897c67451b31f68a3a31a6ee8de756b2b52

Works for me, if I'm violating some Gradle best practices - please let me know.
